### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by sbuttgereit** [ExHammer/hammer-backend-mnesia#1]
Hi--

I started looking at this backend and I noticed that there is no license.  I'm guessing the intent is to use the MIT license like the main ExHammer/hammer library and the ExHammer/hammer-backend-redis backend library do, but don't want to assume this library has been licensed for use at all.

Is ExHammer/hammer-backend-mnesia licensed via the MIT license?

Thanks

**Comment by epinault** [comment]
yes this is MIT license and oging to add it shortly

**Comment by epinault** [comment]
Fixed it now
