### ISSUE TITLE
Support Hammer 6.2

### ISSUE THREAD

**Issue by lobo-tuerto** [ExHammer/hammer-backend-mnesia#24]
**Describe the bug**
If you are using Hammer v6.2, then try to add `hammer-backend-mnesia` to dependencies you'll see:

```bash
Because hammer_backend_mnesia >= 0.6.0 depends on hammer ~> 6.1.0 and your app depends on hammer ~> 6.2, hammer_backend_mnesia >= 0.6.0 is forbidden.
So, because your app depends on hammer_backend_mnesia ~> 0.6, version solving failed.
```

**Provide the following details**

- Elixir version (elixir -v): Elixir 1.16.1 (compiled with Erlang/OTP 26)
- Erlang version (erl -v): Erlang/OTP 26
- Operating system: Linux

**Expected behavior**
I should be able to install `hammer_backend_mnesia` alongside `hammer` 6.2 without problems as there aren't any breaking changes.

Probably relaxing the version spec from `{:hammer, "~> 6.1.0"}` to something like `{:hammer, "~> 6.1"}` or something? :thinking: 

**Actual behavior**
Cannot install along with latest `hammer`.

Thanks! :pray:

**Comment by epinault** [comment]
I just pushed a new version with #25  . let me know if that does not solve your issue
